export enum PrivatePathsEnum {
  PASSWORD_FIRST_LOGIN = '/password-first-login',
  CHANGE_PASSWORD = '/change-password',
  HOME = '/',
  PROJECTS = '/projects',
  CREATE_PROJECTS = '/projects/create-projects',
  UPDATE_PROJECT = '/projects/edit-project',
  CREATE_PROJECT_EMPLOYEES = '/projects/create-project-employees',
  UPDATE_PROJECT_EMPLOYEES = '/projects/update-project-employees',
  PROJECT_DETAILS = '/projects/details',
  EMPLOYEES = '/employees',
  CREATE_EMPLOYEES = '/employees/create_employees',
  UPDATE_EMPLOYEE = '/employees/update-employee',
  EQUIPMENTS = '/equipments',
  CREATE_EQUIPMENTS = '/equipments/create-equipments',
  UPDATE_EQUIPMENT = '/equipments/update-equipment',
  CUSTOMERS = '/customers',
  CREATE_CUSTOMERS = '/customers/create-custormers',
  UPDATE_CUSTOMER = '/customers/update-customer',
  USERS = '/users',
  CREATE_USERS = '/users/create-users',
  UPDATE_USER = '/users/update-user',
  TEMPLATES = '/templates',
}
