export enum ScreenNameEnum {
  ERGONOMIC_EVALUATION_AEP = 'ERGONOMIC_EVALUATION_AEP',
  ERGONOMIC_EVALUATION_AET = 'ERGONOMIC_EVALUATION_AET',
  ROI_SPREADSHEET = 'ROI_SPREADSHEET',
  ELECTROMYOGRAPHY = 'ELECTROMYOGRAPHY',
  KINESIS_FUNCIONAL = 'KINESIS_FUNCIONAL',
}
