import { QueryClient } from '@tanstack/react-query';

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

export enum QueryKeys {
  PROJECTS = 'PROJECTS',
  SHOW_PROJECT = 'SHOW_PROJECT',
  SHOW_PROJECT_EMPLOYEES = 'SHOW_PROJECT_EMPLOYEES',
  USERS = 'USERS',
  SHOW_USER = 'SHOW_USER',
  CUSTOMERS = 'CUSTOMERS',
  SHOW_CUSTOMER = 'SHOW_CUSTOMER',
  EMPLOYEES = 'EMPLOYEES',
  SHOW_EMPLOYEE = 'SHOW_EMPLOYEE',
  EQUIPMENTS = 'EQUIPMENTS',
  SHOW_EQUIPMENT = 'SHOW_EQUIPMENT',
  AUTO_EVALUATIONS = 'AUTO_EVALUATIONS',
  SHOW_AUTO_EVALUATION = 'SHOW_AUTO_EVALUATION',
  EVALUATIONS = 'EVALUATIONS',
  KINESIS_EVALUATIONS = 'KINESIS_EVALUATIONS',
  SHOW_KINESIS_EVALUATION = 'SHOW_KINESIS_EVALUATION',
  SENSORS = 'SENSORS',
  SHOW_SENSOR = 'SHOW_SENSOR',
  ATTENDANCE_LIST = 'ATTENDANCE_LIST',
  MONITORING_EVALUATIONS = 'MONITORING_EVALUATIONS',
  SHOW_MONITORING_EVALUATION = 'SHOW_MONITORING_EVALUATION',
  AUTO_EVALUATIONS_REPORT = 'AUTO_EVALUATIONS_REPORT',
  KINESIS_EVALUATIONS_REPORT = 'KINESIS_EVALUATIONS_REPORT',
  SENSORS_REPORT = 'SENSORS_REPORT',
  TEMPLATES = 'TEMPLATES',
  SHOW_TEMPLATE = 'SHOW_TEMPLATE',
}
